---
name: "Setup WASI SDK"
author: "Vitaly Slobodin"
description: "Set up the WASI SDK for WebAssembly development"
inputs:
  sdk-version:
    description: "WASI SDK version"
    required: false
    default: "24"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    SDK_VERSION: ${{ inputs.sdk-version }}
branding:
  color: "gray-dark"
  icon: "archive"
