---
name: "Setup WASI SDK"
author: "Vitaly Slobodin"
description: "Set up the WASI SDK for WebAssembly development"
inputs:
  sdk-version:
    description: "WASI SDK version"
    required: true
    default: "24"
runs:
  using: "composite"
  steps:
    - run: |
        docker pull ghcr.io/webassembly/wasi-sdk:wasi-sdk-${{ inputs.sdk-version }}
      shell: bash
branding:
  color: "gray-dark"
  icon: "archive"
